### PR TITLE
Update JobID45_en_it.xlf

### PR DESCRIPTION
**Pull request by fvalle1**

### CODE REVIEW

**Comment by fvalle1** [comment]
ok I deleted other files and removed the other pull request...

Now this should be just an edited version...

Sorry...:-)

**Comment by mfb** [comment]
Great thanks! FYI, if I recall correctly there were still some strings in https://github.com/EFForg/www-l10n/blob/master/translations/it/JobID27_en_it.xlf that were not translated yet.

**Comment by fvalle1** [comment]
Ok, I'will work on that!

**Comment by fvalle1** [comment]
Ok, I'will work on that!

**Pull request merged**
