### PR TITLE
[Turkish] Update JobID35_en_tr.xlf

### PR DESCRIPTION
**Pull request by ghost**
This is a significant update. Only a few strings left (the big ones). I'll probably finish translating this week. (After hearing from you.)

(I'm only creating this pull request to see if there's any technical problems. If there is, let me know.)

### CODE REVIEW

**Comment by mfb** [comment]
I merged your pull request, and we could go ahead and import it to the site if you think it's ready?

**Comment by ghost** [comment]
Nope, it's not! Only about %40 of it is finished. I've created the pull request so you could check whether the translations work or not. The app I'm using got updated, which broke the XLIFF editor for the file I'm working on but I got in touch with the developer and he sent me a version of the app that works with your XLIFF file. That prompted me to create this pull request because I wanted to make sure the new version of the app was working as intended before translating anymore. I've been waiting for you to confirm that for me. Once you do, I'll start translating. Thanks.

**Comment by mfb** [comment]
It works. I still get errors about unable to automatically validate the file, but we can work with this via manual review if it's the best we can do. Thanks!

**Comment by ghost** [comment]
Great! Unfortunately it seems to be the only way. It's not ideal for me too but we gotta make it work somehow. I'll start translating in a day or two, if not today. I have another project that's been keeping me busy but I plan on finishing that today. I'll jump right on this as soon as I'm done with the other one. Thanks!

**Pull request merged**
